apiVersion: v1
kind: Pod
metadata:
  name: mod_matchfunction
  namespace: openmatch
  labels:
    app: openmatch
    component: mod_matchfunction
spec:
  containers:
  - name: mod_matchfunction
    image: localimage/mod_matchfunction:0.1
    imagePullPolicy: Never
    ports:
    - name: grpc
      containerPort: 50502
---
kind: Service
apiVersion: v1
metadata:
  name: mod_matchfunction
  namespace: openmatch
  labels:
    app: openmatch
    component: mod_matchfunction
spec:
  selector:
    app: openmatch
    component: mod_matchfunction
  clusterIP: None
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 50502
